### ISSUE TITLE
broken links in install procedure

### ISSUE THREAD

**Issue by kurthalex** [jancelin/docker-lizmap#11]
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/var/jauth.db
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/var/logs.db
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/var/config/lizmapConfig.ini.php

**Comment by jancelin** [comment]
changing : https://github.com/jancelin/docker-lizmap/commit/d8c81a3da6d43cd6879d2c40be1823a17e2aa441
