### ISSUE TITLE
default login/pass to access admin interface

### ISSUE THREAD

**Issue by kurthalex** [jancelin/docker-lizmap#12]
I followed the install procedure
But when I type  http://myserver:8081/websig/lizmap/www/admin.php
there is the lizmap connexion page, but in the install procedure does not provide login/password to connect to the admin interface. And admin/admin does not work.

Sorry if it was not an issue.

thanks

**Comment by jancelin** [comment]
Hi.
If it s a new jauth.db : 
login :admin 
Passwd :admin

If it s your jauth.db
Your login, passwd

It s the first time I look this bug....
Mail me with phone if it s continue.

**Comment by kurthalex** [comment]
Sorry, I made a stupid mistake . It works, you can close the issue.

I did this :
wget https://github.com/3liz/lizmap-web-client/blob/2.11.1/lizmap/var/jauth.db
It did not download the raw file, so it could not work.

**Comment by jancelin** [comment]
solution if admin.php do not save ( error 500)

sudo chown www-data:www-data -R /"your config path"

**Comment by jlstanus** [comment]
I get this problem with the last master
first use and it says

admin
admin

is noot correct password
