### ISSUE TITLE
Jauth : Fatal error PHP

### ISSUE THREAD

**Issue by raphadasilva** [jancelin/docker-lizmap#17]
Bonjour,

merci pour ce beau geoppy. J'ai tenté de m'en fabriquer un hier, mais ça a coincé sur mon Raspberry Pi 3 à l'étape du docker lizmap. 

J'ai testé également avec un Raspberry 2 au cas où, et il y a toujours la même erreur au même endroit. Ca concerne le module jauthdb, et l'erreur est décrite comme suit :

 PHP Fatal error : Call to a member function getValue() on null in /var/www/websig/lib/jelix-modules/jauth/install/install.php on line 49

C'est bien embêtant parce qu'après, pas moyen de se connecter à Lizmap via l'adresse 10.10.0.25, en suivant précisément votre tuto comme les recommandations de ce post : https://github.com/jancelin/docker-lizmap/issues/15

Avez-vous déjà rencontré ce souci ?

Merci d'avance !

**Comment by jancelin** [comment]
Salut, 
Ici c'est la version serveur ou pc.
je ferme, tu peux réouvrir l'issue ici:

https://github.com/jancelin/rpi-docker-lizmap

j'ai bien vu le bug, je regarde...
