### ISSUE TITLE
After reboot Docker doesn't restart

### ISSUE THREAD

**Issue by hoge6b01** [jancelin/docker-lizmap#20]
Hello,
I installed your docker as described and worked for weeks like charm. Today I had to restart the server. But docker restart lizmap does not restart the docker. A docker ps -a shows that it's restarting since About a minute ago. But since ten minutes it shows the same. So my question is what do I have to do after a server's reboot?

Thanks in advance.

**Comment by hoge6b01** [comment]
re-installed everything and now it's restarting like charm. Sorry for setting up an issue.

**Comment by jancelin** [comment]
the important thing is that it works. welcome

**Comment by hoge6b01** [comment]
maybe you can clearify one thing. the configuration shows /tmp/ as the 
cache's folder. when hitting the 'save' button (without changing 
anything) it gives an error saying to choose a folder where apache2 has 
the right to write to.

Should I define a folder outside the container or stay with the 
/tmp/-folder?

Thanks

Carsten


Am 16.09.2016 um 14:25 schrieb ANCELIN Julien:

**Comment by hoge6b01** [comment]
Sorry, but I have to re-open this issue. 
I'm trying the docker with a Ubuntu Server 16.04. 
After rebooting the server Docker cannot restart the volume. What is wrong with it?
Here a screenshot:
![docker](https://cloud.githubusercontent.com/assets/5871910/18626647/9203b82c-7e56-11e6-98de-3ddb6a34f99a.JPG)

**Comment by jancelin** [comment]
You need run it interactively.

```docker run -ti  -restart="always" --name "lizmap" ...```

Explanation
```
   -t, --tty=false                     Allocate a pseudo-TTY
   -i, --interactive=false         Keep STDIN open even if not attached
```

**Comment by hoge6b01** [comment]
Well, it always works for the first/second restart of the server. After
that it gets back to the problem of not being able to restart. Did you try
various restarts with your installation?
Thanks

2016-09-19 12:10 GMT+02:00 ANCELIN Julien <notifications@github.com>:

**Comment by hoge6b01** [comment]
now
`docker logs --tail 50 --follow --timestamps lizmap`

gives me

`apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message

httpd (pid 7) already running`

does this help you?

**Comment by jancelin** [comment]
I have no problem on my side but I use a lot docker-compose.yml.

I do not uses -it with docker-compose, you can try without?

**Comment by hoge6b01** [comment]
Digged somehow deeper into the problem.
Seems really to depend on the existing [PID](https://github.com/docker-library/php/issues/53).
I don't know how to solve.
Which OS are you using?

**Comment by jancelin** [comment]
https://github.com/jancelin/docker-lizmap/commit/c5e8af104eab1f27a60529a24f4444822db16687

you can test please.

```docker pull jancelin/docker-lizmap:3-2.14LTR```

**Comment by SidneyEvo** [comment]
Hello guys did you find a solution ? Because I have the same problem. ' httpd (pid 7) already running '

**Comment by jancelin** [comment]
you have to reload the new image?
because I added ```rm -f /var/run/apache2/apache2.pid``` at start now.

Stop container, remove it, remove images (docker rmi ...) and ```docker pull jancelin/docker-lizmap:3-2.14LTR```

**Comment by jancelin** [comment]
have you tested?

**Comment by SidneyEvo** [comment]
Im sorry I used a different image , but had the same problem. Now it's ok because it was a bug. Thanks for your effort btw.

Cheers

**Comment by hoge6b01** [comment]
Thanks for the proposed solution. I set up a watchdog script so I didn't try your suggestion.
My script:

`#!/bin/sh

TMPFILE='mktemp'
WAITTIME=5

# Run the test
wget --spider http://[yourURL]/websig/lizmap/www/themes/default/css/img/logo_footer.png 2>$TMPFILE

# Wait few seconds and let the test finish
sleep $WAITTIME

if [ ! `grep "HTTP-Anforderung gesendet" $TMPFILE |grep "200 OK"|wc -l` -gt 0 ]; then
    echo "The service did not return 200 in $WAITTIME seconds."
    echo "Restarting in."
   sudo docker stop lizmap && docker rm lizmap && docker run --restart="always" --name "lizmap" -p 80:80 -d -t \
-v /home/lizmap_project:/home \
-v /home/lizmap_var:/var/www/websig/lizmap/var \
-v /home/lizmap_tmp:/tmp \
jancelin/docker-lizmap 
fi

# Cleanup
rm $TMPFILE
pkill wget`
