### ISSUE TITLE
Problem with /tmp folder

### ISSUE THREAD

**Issue by igeofr** [jancelin/docker-lizmap#21]
Hi and thanks for your work.
As expected, I open this ticket.

When I want to configure Lizmap, I have a problem to access the directory : tmp.
"Le répertoire n'existe pas où n'est pas accessible en écriture. Vous pouvez utiliser: /tmp"

However, when I delete it with the following command   -v /tmp, then  I can edit the configuration.

Thanks

**Comment by jancelin** [comment]
try 

chown :www-data -R /.../tmp on host
and maybe chmod 775 -R /.../tmp

**Comment by igeofr** [comment]
Pour revenir sur mon message d'hier, les commandes suivantes ont été lancées directement dans le container et non pas dans l'hôte : 
sudo docker exec -it lizmap bash
chown :www-data -R /tmp
chmod 775 -R /tmp

**Comment by jancelin** [comment]
hum hum, 

Essaye avec l'hôte: 
```
mkdir /home/lizmap_tmp
chown :www-data -R /home/lizmap_tmp && chmod 775 -R /home/lizmap_tmp
```
Tu peux essayer de relancer un nouveau container avec le  ```-v /home/lizmap_tmp:/tmp ```

**Comment by jancelin** [comment]
Il me manquait une ligne dans le dockerfile, j'attends l'update dans le dockerhub et tu pourra reconstruire l'image dans 5 min.

**Comment by jancelin** [comment]
essaye: ```docker pull jancelin/docker-lizmap:3-2.14LTR```

**Comment by igeofr** [comment]
Je viens de faire le test avec docker-lizmap:3-2.14LTR et je n'ai pas eu de problèmes.

Merci d'avoir pris le temps de résoudre ce problème.

**Comment by jancelin** [comment]
de rien :)
à plus

**Comment by igeofr** [comment]
Juste pour terminer la ligne : chown :www-data -R /home/lizmap_tmp && chmod 775 -R /home/lizmap_tmp peut donc être supprimée du read me.
