### ISSUE TITLE
Problèmes avec l'impression en utilisant les motifs de ligne

### ISSUE THREAD

**Issue by MickaelH974** [jancelin/docker-lizmap#22]
Bonjour,

Lors d'une impression utilisant des symboles "motif de ligne", l'on a un retour d'erreur 500 de apache.

J'utilise lizmap 3.0.1 et Qgis-server 2.14 (Sur http://www.itopen.it/qgis-server-setup-notes/  il semblerai que cela vienne du serveur X qui probablement n’existe pas dans le contenair)

Cordialement.

**Comment by jancelin** [comment]
salut,

essaye de rentrer dans le container 

```docker exec -it ton_nom_de_container bash```

et d'installer ton serveur x comme dans ton lien:

```apt-get install xvfb```

si ça marche dis le moi je le rajouterai au dockerfile.
Tu peux aussi mettre à jour ton image si ça marche:
```docker commit ton_nom_de_container ton_nom_d_image```

**Comment by MickaelH974** [comment]
Ca ne marche pas pour moi malgré l'installation de xvfb. Et lorsque j'applique la configuration, proposé, qgis-server ne fonctionne même plus dans lizmap. Je vais refaire des tests et je te tiens au courant

**Comment by jlstanus** [comment]
Hello, pareil. 
J'ai testé http://www.itopen.it/qgis-server-setup-notes/ ceci dans le container sans succès.
Ca casse le GIS.
