### ISSUE TITLE
add tag for 2.16.2

### ISSUE THREAD

**Issue by mbernasocchi** [jancelin/docker-lizmap#23]
Hi @jancelin could you add a tag for 2.16.2/3.0.3 I've successfully used it (using latest) to build my docker compose including PotGIS (https://github.com/opengisch/docker-lizmap-postgis/) and i'd be great to be able to use a tagged version.

thanks for all the work
Marco

**Comment by jancelin** [comment]
Hi, 
I have to tag the picture. it goes on qgis 2.18( a new version was available).
However, I recommend using the 3-2.14LTR.
I built the lastest with qgis 2.18 and lizmap master (3.1pre).

```
docker pull jancelin/docker-lizmap:3-2.14LTR
docker pull jancelin/docker-lizmap:3.0.3-2.18
docker pull jancelin/docker-lizmap:latest
```
