### ISSUE TITLE
Cannot load map

### ISSUE THREAD

**Issue by hoge6b01** [jancelin/docker-lizmap#39]
Hi,
I updated my docker-lizmap today via `sudo docker pull jancelin/docker-lizmap`.

As I can see in Lizmap Admin UI the running version is Version 3.2pre171102 now. So Update worked. 

But, if I want to load a map (e.g. the Montpellier one) I get server errors. Here are the logs:

> 2018-01-17 11:58:20	80.149.89.58	notice	2018-01-17 11:58:20	[8]	Undefined index: logEmail	/var/www/websig/lizmap/modules/lizmap/classes/lizmapLogItem.class.php	69

> 2018-01-17 11:58:20	80.149.89.58	notice	2018-01-17 11:58:20	[8]	Undefined index: logEmail	/var/www/websig/lizmap/modules/lizmap/classes/lizmapLogItem.class.php	69

> 2018-01-17 11:58:20	80.149.89.58	warning	2018-01-17 11:58:20	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Fwebsig%2Flizmap%2Finstall%2Fqgis%2Fmontpellier%2Eqgs&amp;request=GetCapabilities&amp;service=WMS&amp;version=1%2E3%2E0): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
	/var/www/websig/lizmap/modules/lizmap/classes/lizmapProxy.class.php	93

> 2018-01-17 11:58:20	80.149.89.58	warning	2018-01-17 11:58:20	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Fwebsig%2Flizmap%2Finstall%2Fqgis%2Fmontpellier%2Eqgs&amp;request=GetCapabilities&amp;service=WFS): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
	/var/www/websig/lizmap/modules/lizmap/classes/lizmapProxy.class.php	93

What happend? Did I download the wrong version? Do I have to do other steps as well?
Thanks for your help!
Carsten

**Comment by jlstanus** [comment]
I had the same.
I changed the qgisserver 2.18 image instead of 2.14.
Then, you have to change in administrator setting 2.14 to 2.18.
If _/tmp/_ does matter go into the docker instance (`docker exec -ti nameofthecontainer bash`) then
 `chmod 775 -R /tmp && chown :www-data -R /tmp`

**Comment by hoge6b01** [comment]
I followed your steps but I still get the same error like described above. QGISServer is set to ≥ 2.18 and I executed the chmod & chown commands. Any idea?

**Comment by jlstanus** [comment]
Did you use docker-compose or docker alone? are you sure that the 2
containers are runnning?

Else, try to restart the docker-compose

Cordialement,

Jean-Louis Stanus


----


Jean-louis Stanus
[image: https: //]about.me/jl.stanus
<https://about.me/jl.stanus?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

☎ +32 473761482


2018-01-17 13:12 GMT+01:00 hoge6b01 <notifications@github.com>:

**Comment by hoge6b01** [comment]
I only did what I wrote in my first message. 
I checked for running docker with `sudo docker ps` and this is my running docker (see image).
You think thats wrong?
![image](https://user-images.githubusercontent.com/5871910/35049508-88b36880-fba0-11e7-95b6-9c44091ac005.png)

**Comment by jlstanus** [comment]
It looks like the qgisserver container is missging ;) I see only lizmap container running
Did you use `docker-compose up` ?

**Comment by hoge6b01** [comment]
Sorry again for my nooby questions:
1. Do I have to uninstall dockers first?
2. I used this .yml file [here](https://github.com/jancelin/docker-lizmap/blob/3.1.5/docker-compose.yml).
3. Had to change the .yml file and set `version: '3' ` to `version: '2'`.
4. `docker-compose up -d` started to download qgisserver but stopped with the following:
![image](https://user-images.githubusercontent.com/5871910/35051002-8225cdce-fba4-11e7-8b76-a6762bc1a0b3.png)

**Comment by jlstanus** [comment]
Of course

docker stop 0be6bf ..... or by the name that use already ports 80 and 443
Then `docker-compose up -d`

**Comment by jancelin** [comment]
if you want to use qgis 2.18, change image name in .yml: jancelin/qgis-server:2.18-wfsOutputExtension
to go back from scratch with compose:

```
docker-compose stop 
docker-compose rm
docker-compose up -d
```

**Comment by hoge6b01** [comment]
okay, only the two containers from the .yml are running. It's an 'clean' install. That means that my projects are gone aswell. Is it possible to get my projects into the new 'installation'?

**Comment by jancelin** [comment]
Put your qgis project + lizmap plugin file in same directory like the .yml:  
```
volumes:
- /home/lizmap/lizmap_project:/home
```

For me: 
/home/lizmap/lizmap_project

go to the lizmap back office:
http://xxx.xxx.xxx.xxx/websig/lizmap/www/admin.php/config/

change qgis server url: 127.0.0.1 to qgisserver
add identify, name and directory: /home 
check user.

**Comment by jancelin** [comment]
you can start more than one container on the same directory and if a crash container the data is kept.

**Comment by hoge6b01** [comment]
> Put your qgis project + lizmap plugin file in same directory 
worked!
But I've got a lot of projects that now I have to configurate in lizmap's admin interface. 
Is there any way to get the configuration from the old container?

**Comment by jancelin** [comment]
cp paste your /var directory like /lizmap/project:

```
volumes:
     - /home/lizmap/project:/home
     - /home/lizmap/project/var:/var/www/websig/lizmap/var
```
To retain file permissions do a 

```
cp -avr /....
```
