### ISSUE TITLE
[Feature] Install & configure fake xserver to print PDF

### ISSUE THREAD

**Issue by jlstanus** [jancelin/docker-lizmap#40]
Hello @jancelin  ,

is there any reason to not install xvfb package and configure it?

http://www.itopen.it/qgis-server-setup-notes/

**Comment by jlstanus** [comment]
Always not possible to print pDF but PNG, SVG too

Where can i find the error.log from apache?

![image](https://user-images.githubusercontent.com/402354/38235908-f2f11eaa-3722-11e8-9171-14d6708ea23f.png)

**Comment by jlstanus** [comment]
To activate the the xserver : 

1. List the containers and get the id of the **qgis server** (not lizmap) container. For exemple container id  _09458996bc1c_ 
2. Go into `docker exec -ti 09458996bc1c bash` 
3. Follow steps [here](http://www.itopen.it/qgis-server-setup-notes/)
4. Leave the container `exit`
5. docker-compose restart. Opening the project should give an error
6. go back in the qgis server container and execute the following command line `Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &`

**Comment by kikislater** [comment]
Thanks jl
Could be a PR in docker-qgis-server in my opinion !

**Comment by jlstanus** [comment]
;-) 
This is happening in the _debian:jessie_ image, not the lizmap one. I don't know the best way to modify only the debian image. But interested to learn @jancelin

**Comment by kikislater** [comment]
Basically without testing : 

**1 -** in Dockerfile here : https://github.com/jancelin/docker-lizmap/blob/master/Dockerfile
You could add `xvfb` in line 8 before \

**2 -** in fcgid.conf :  https://github.com/jancelin/docker-lizmap/blob/master/files/fcgid.conf between line 14 and 15
```
# Pass display number to QGIS MapServer instances
 FcgidInitialEnv DISPLAY ":99"
```

**3 -** Add a new file in file folder : https://github.com/jancelin/docker-lizmap/tree/master/files called 
**xvfb.service**  with the following 
```
[Unit]
Description=X Virtual Frame Buffer Service
After=network.target

[Service]
ExecStart=/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &

[Install]
WantedBy=multi-user.target
```
Source : https://gist.github.com/ypandit/f4fe751bcbf3ee6a32ca

**4 -** Add this line at line 18 in setup.sh here : https://github.com/jancelin/docker-lizmap/blob/master/files/setup.sh
`mv /home/files/xvfb.service && chmod +x /etc/systemd/system/xvfb.service  && systemctl enable xvfb.service && systemctl start xvfb.service`

**Comment by jlstanus** [comment]
You are right on the command lines but not on the repository.
This has to be done in the [docker-qgis-server](https://github.com/jancelin/docker-qgis-server/blob/LTR/Dockerfile)  repository not here

**Comment by kikislater** [comment]
Yes agree sorry !

**Comment by jlstanus** [comment]
yes ;-)

**Comment by kikislater** [comment]
Do you want to do it ? 
If not I could ;-)

**Comment by jlstanus** [comment]
You can if not i ll do it later.
It's your proposition. 😜

Cordialement,

Jean-Louis Stanus


----


Jean-louis Stanus
[image: https: //]about.me/jl.stanus
<https://about.me/jl.stanus?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

☎ +32 473761482


2018-04-25 14:55 GMT+02:00 Sylvain POULAIN <notifications@github.com>:

**Comment by jancelin** [comment]
xvfd available in the jancelin/docker-qgis-server:2.18LTR !!! finally took the time to do it...
But I can't print the background maps as google-satellite or osm-mapnik :( 

Can you test?

**Comment by jancelin** [comment]
@jlstanus can you print background with lizmap?

**Comment by jlstanus** [comment]
i will reinstall this docker in the next weekds, i keep you in touch
