### ISSUE TITLE
SSL Certificate - Error

### ISSUE THREAD

**Issue by hoge6b01** [jancelin/docker-lizmap#42]
When I surf to my docker-lizmap installation via https it returns me 

> NET::ERR_CERT_AUTHORITY_INVALID

It seems because the cert is issued by '9306447c14e2' which seems not to be a trusted issuer.
So my question is: does docker-lizmap comes with a 'default' cert? Do I have to get one for my installation?

Sorry for my nooby question.
Thanks and BR!

**Comment by Doctor-Who** [comment]
Hi,
It's a self cert, only verified SSL by registrar are good for your browser that because you've got that error message.
So you just ignore and continue into your browser and it will works

**Comment by hoge6b01** [comment]
Thanks for your answer.
