### ISSUE TITLE
[nightly] Are you trying to mount a directory onto a file?

### ISSUE THREAD

**Issue by MaxiReglisse** [jancelin/docker-lizmap#68]
branch nightly, "docker-compose up -d " fails with the following error:

    [docker@lizmap-test docker-lizmap (nightly)]$ docker-compose up -d
    Removing docker-lizmap_nginx_1
    Recreating 01cd780f2db5_docker-lizmap_nginx_1 ... 
    docker-lizmap_redis_1 is up-to-date
    docker-lizmap_qgiserver_1 is up-to-date
    Recreating 01cd780f2db5_docker-lizmap_nginx_1 ... error

    ERROR: for 01cd780f2db5_docker-lizmap_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/docker/docker-lizmap/lizmap/nginx/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/06e52221c465c522ee053b5e472bb159b7bf28d1e109af5312bcf9c3eb3f6975/merged\\\" at \\\"/var/lib/docker/overlay2/06e52221c465c522ee053b5e472bb159b7bf28d1e109af5312bcf9c3eb3f6975/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

    ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/docker/docker-lizmap/lizmap/nginx/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/06e52221c465c522ee053b5e472bb159b7bf28d1e109af5312bcf9c3eb3f6975/merged\\\" at \\\"/var/lib/docker/overlay2/06e52221c465c522ee053b5e472bb159b7bf28d1e109af5312bcf9c3eb3f6975/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
    ERROR: Encountered errors while bringing up the project.

any help would be appreciated

**Comment by kikislater** [comment]
It's written on readme : 

>     With Docker-compose:

>     Copy nginx.conf to ./lizmap/nginx/nginx.conf

**Comment by MaxiReglisse** [comment]
oups... sorry !

thanks Kikislater.
